version: 18
jobs:
- name: Build Docker Image
  steps:
  - !BuildImageStep
    name: Build Docker Image
    buildPath: '@project_name@'
    dockerfile: '@project_name@'
    tags: rymcu/nebula:latest
    publish: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !TagCreateTrigger
    projects: nebula
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
